var myObject = {
    name: "Muntaha",
    FName: "Asif",
    Qualification: "Enter",
    MatricField: "ComputerScience",
    EnterField: "Commerce",
    Hobby1: "ReadingBooks",
    Hobby2: "Cooking",
    Hobby3: "scetching",
    Course: "WebDevelopment",
    number: "0370-5967581",
    Email: "muntahaasif@780gmail.com",
    Siblings: "2",
    Sisters: "1",
    Brother: "1",
    MotherName: "Sabiha",
    SchoolName: "SunRiseChildrenAcademy",
    CollegeName: "KhursheedGovernmentGirlsCollege",
    City: "Karachi",
    Country: "Pakistan",
    MaritalStatus: "Single",
    Campus: "MalirCampus",
    FavDish: "Biryani",
    FavAnimal: "BabyLion",
    Age: 19,
    Address: "Ammar-e-yasirPhase#1",
    HouseNum: "649/96",
    TeacherName: "MissMinahil",
    Gender: "Female",
    PostalCode: "0000",
    FriendsName: ["Heed", "Ashara", "Inza"],
    Religion: "Islam",
    FavSubject: ["Accounts", "Islamiat", "English"],
    Skill1: "HTML",
    Skill2: "CSS",
    Skill3: "JavaScript",
    YearOfExperience: "2Years",
    Snap: "syeda-muntaha",
    Instagram: "muntaha-asif",
    FaceBook: "muntaha-asif",
    LinkIndin: "MuntahaAsif",
    FavColor: "Black",
    Sports: "Badminton",
    Device: "Laptop",
    Languages: ["English" , "Urdu"],
    MotherTongue: "Urdu",
    InstituteName: "SMIT",
    Phone: "GooglePixel6",
    FavCountry: "Turkey",
    isStudent: true,
    LaptopBrand: "Dell",
    FavSeason: "Winter",
    FavBrand: "AghaNoor",
    FavCar: "LandCruiser",
    BirthYear: "2006",
    DOB:"26-2-2006",
    FavNovel: "Peer-e-kamil",
    
    
}
console.log(myObject);